#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradlew ...
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+set}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   (2) Important for developers:
#
#       The 'gradlew' script must be executable.
#
#       When you are using this script on your workstation, all you have to do
#       is setting the 'x' bit. On Unix-like systems this is done by command:
#
#           chmod +x gradlew
#
#       in project root.
#
#       When you are pushing this script to git repository, please ensure to
#       set the 'x' bit. On Unix-like systems this is done by command:
#
#           git update-index --chmod=+x gradlew
#
#   (3) Important for CI:
#
#       The 'gradlew' script must be executable.
#
#       You can either fix the git index via command above or setting the
#       'x' bit in the CI configuration.
#
##############################################################################

set -o errexit

appNameBase=$(basename "$0")
appName="${appNameBase%.*}"
# make sure the name of the app is unique
pid=$$

# If we run the script via "sh gradlew" (e.g. BusyBox), the $0 is "gradlew" and
# we cannot locate the wrapper jar relative to it.
# We fallback to the current directory.
# But if we execute "./gradlew", the $0 is "./gradlew" and we can resolve correctly.
if [ "$0" = "gradlew" ] || [ "$0" = "./gradlew" ]; then
    APP_HOME="."
else
    # The current directory is assumed to be the root of the project
    APP_HOME=$(dirname "$0")
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Function directly mimicks the Gradle internal mechanism for finding java home
# logic (see org.gradle.internal.jvm.Jvm.java)
find_java_home() {
    # If JAVA_HOME is set, check it first
    if [ -n "${JAVA_HOME:-}" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            # IBM's JDK on AIX uses strange locations for the executables
            echo "$JAVA_HOME/jre/sh/java"
            return
        elif [ -x "$JAVA_HOME/bin/java" ] ; then
            echo "$JAVA_HOME/bin/java"
            return
        fi
    fi

    # Check for java in PATH
    if command -v java >/dev/null 2>&1 ; then
        echo "java"
        return
    fi
    
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    echo "" >&2
    echo "Please set the JAVA_HOME variable in your environment to match the" >&2
    echo "location of your Java installation." >&2
    exit 1
}

JAVACMD=$(find_java_home)

# Increase code consistency in error messages between POSIX and Windows
die() {
    echo ""
    echo "$*"
    echo ""
    exit 1
}


# Split strings into array
# $1 - string
# $2 - delimiter
# $3 - array name
split() {
    local IFS=$2
    eval $3="($1)"
}

# Determine the Java command to use to start the JVM.
if [ -z "$JAVACMD" ] ; then
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            # IBM's JDK on AIX uses strange locations for the executables
            JAVACMD="$JAVA_HOME/jre/sh/java"
        else
            JAVACMD="$JAVA_HOME/bin/java"
        fi
    else
        JAVACMD="java"
    fi
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Build standard options
opts=""
args=""

# Process arguments
for arg in "$@" ; do
    if [ "$arg" = "--" ] ; then
        shift
        break
    fi
    # Add to arguments
    args="$args \"$arg\""
    shift
done

# Collect all arguments for the java command
set -- $args

# Execute Gradle
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
